package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    ENTERO,DECIMAL, IDENTIFICADOR,OPERADOR_LOGICO,DESCONOCIDO,DATO_ENTERO,
    DATO_REAL,DATO_CARACTER,CARACTER,DATO_STRING,DATO_BOOLEAN,BOOLEAN,OPERADOR_ASIGNACION,COMENTARIO_BLOQUE,
    CONDICION_If,CONDICION_ELSE,SWITCH,BREAK,ITERADOR_FOR,CICLO_WHILE,CLASE,PROCEDIMIENTO,FUNCION,
    CONSTANTE,OPERADOR_AGRUPACION,OPERADOR_SEPARACION,BLOQUE_SENTENCIA,OPERADOR_INCREMENTO,
    OPERADOR_DECREMENTO,PUNTO,DOS_PUNTOS,OPERADOR_ARITMETICO,OPERADOR_TERMINAL,RETORNO,LECTURA,IMPRESION,CASO,CADENA,OPERADOR_RELACIONAL, BLOQUE_ARREGLO
}